appname: "cyberman"
layout: "main"
charset: "UTF-8"
auto_page: 1

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'

plugins:
  Database:
    driver: 'SQLite'
    dbname: 'db.sqlite'
    log_queries: 1
