appname: "cyberman"
layout: "main"
charset: "UTF-8"
auto_page: 1

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'

plugins:
  Database:
    driver: 'SQLite'
    dbname: 'db.sqlite'
    log_queries: 1

tld: 'cyb'

zonewriter:
  # Values used for SOA
  ns: 'ns12.opennic.glue'
  responsible: 'hostmaster.opennic.cyb.'
  file: '/var/nsd/zones/master/cyb'
  include:
    # Optionally, you can have the zonewriter include another file
    # in the zone, which allows you to define some records manually
    enabled: true
    file: 'human_cyb'
